const env = {
    VITE_HRIS_BACKEND_URL: import.meta.env.VITE_HRIS_BACKEND_URL,
    VITE_PAYROLL_BACKEND_URL: import.meta.env.VITE_PAYROLL_BACKEND_URL,
    VITE_PAYROLL_SERVICE_ID: import.meta.env.VITE_PAYROLL_SERVICE_ID,
    VITE_PAYROLL_PAYRUNS_VIEW: import.meta.env.VITE_PAYROLL_PAYRUNS_VIEW,
    VITE_PAYROLL_DAILY_RECORDS: import.meta.env.VITE_PAYROLL_DAILY_RECORDS,
    VITE_PAYROLL_GENERATE_PAYRUN: import.meta.env.VITE_PAYROLL_GENERATE_PAYRUN,
    VITE_PAYROLL_CHANGE_PAYRUN_STATUS: import.meta.env.VITE_PAYROLL_CHANGE_PAYRUN_STATUS,
    VITE_PAYROLL_DELETE_PAYRUN: import.meta.env.VITE_PAYROLL_DELETE_PAYRUN,
    VITE_PAYROLL_EDIT_PAYRUNS: import.meta.env.VITE_PAYROLL_EDIT_PAYRUNS,
    VITE_PAYROLL_CONFIGURE_PAYRUN_SETTING: import.meta.env.VITE_PAYROLL_CONFIGURE_PAYRUN_SETTING,
    VITE_PAYROLL_CONFIGURE_CONTRIBUTIONS_SETTING: import.meta.env.VITE_PAYROLL_CONFIGURE_CONTRIBUTIONS_SETTING,
    VITE_PAYROLL_EMPLOYEE_MANAGEMENT: import.meta.env.VITE_PAYROLL_EMPLOYEE_MANAGEMENT,
    VITE_PAYROLL_RECURRING_PAYS: import.meta.env.VITE_PAYROLL_RECURRING_PAYS,
    VITE_PAYROLL_DATA_EXPORTS: import.meta.env.VITE_PAYROLL_DATA_EXPORTS
}

export default env;