export const payitemsMap = new Map([
    ["13th Month Bonus - Non-Taxable", "payitem-id-15"],
    ["13th Month Bonus - Taxable", "payitem-id-14"],
    ["14 Month", "payitem-id-17"],
    ["14th Month Pay", "payitem-id-17"],
    ["14th Month Pay - Non-Taxable", "payitem-id-17"],
    ["14th Month Pay (Non-Taxable)", "payitem-id-17"],
    ["Absences", "payitem-id-33"],
    ["Anniversary / Quarterly Bonus (Non-Taxable)", "payitem-id-12"],
    ["Anniversary Bonus", "payitem-id-19"],
    ["Anniversary Bonus (Taxable)", "payitem-id-19"],
    ["Augmented Pay", "payitem-id-29"],
    ["Basic Pay", "payitem-id-02"],
    ["Clothing and Laundry Allowance (de Minimis)", "payitem-id-30"],
    ["Company Advances", "payitem-id-51"],
    ["Company Advances Repayment", "payitem-id-51"],
    ["ESPP Deduction", "payitem-id-51"],
    ["HDMF (EE)", "payitem-id-43"],
    ["HDMF (ER)", "payitem-id-44"],
    ["HDMF Loan", "payitem-id-45"],
    ["Housing Allowance - Non-Taxable Pay", "payitem-id-30"],
    ["Meal Allowance (taxable)", "payitem-id-30"],
    ["Medical Allowance (Taxable)", "payitem-id-30"],
    ["Night Differential", "payitem-id-03"],
    ["Night Differential OT", "payitem-id-03"],
    ["Other (Non-Taxable)", "payitem-id-30"],
    ["Other Company Deduction", "payitem-id-52"],
    ["Other Deduction - Housing Deduction", "payitem-id-52"],
    ["Other Non Taxable Pay", "payitem-id-30"],
    ["Other Non-Taxable Pay", "payitem-id-30"],
    ["Other Pay (Non-Taxable)", "payitem-id-30"],
    ["Other Pay (Taxable)", "payitem-id-29"],
    ["Other Pay Deduction - Non-Taxable", "payitem-id-49"],
    ["Other Pay Deduction - Taxable", "payitem-id-49"],
    ["Other Pay Deduction Taxable", "payitem-id-49"],
    ["Other Pay/ Bonus (Taxable)", "payitem-id-29"],
    ["Other Pay/Bonus (Taxable)", "payitem-id-29"],
    ["Other Taxable Pay", "payitem-id-29"],
    ["PHIC (EE)", "payitem-id-46"],
    ["PHIC (ER)", "payitem-id-47"],
    ["PHIC EE", "payitem-id-46"],
    ["Previous Period - Absences & Undertime", "payitem-id-33"],
    ["Previous Period Adjustment - Absences & Undertime", "payitem-id-29"],
    ["PTO Conversion", "payitem-id-11"],
    ["Quarterly Bonus", "payitem-id-12"],
    ["Recurring Other Pay - Non-Taxable", "payitem-id-26"],
    ["Recurring Other Pay/ Bonus (Non- Taxable)", "payitem-id-26"],
    ["Recurring Other Pay/ Bonus (Taxable)", "payitem-id-25"],
    ["Recurring Other Pay/Bonus (Non-Taxable)", "payitem-id-26"],
    ["Recurring Other Pay/Bonus (Taxable)", "payitem-id-25"],
    ["Recurring Other Taxable Pay", "payitem-id-25"],
    ["Regular Holiday", "payitem-id-07"],
    ["Regular Holiday ND OT", "payitem-id-09"],
    ["Regular Holiday Night Differential", "payitem-id-07"],
    ["Regular Holiday OT", "payitem-id-09"],
    ["Regular Holiday Premium Pay", "payitem-id-06"],
    ["Regular OT", "payitem-id-07"],
    ["Reimbursements", "payitem-id-32"],
    ["Reimbursements From Company", "payitem-id-32"],
    ["Rest Day", "payitem-id-04"],
    ["Rest Day ND", "payitem-id-04"],
    ["Rest Day ND OT", "payitem-id-10"],
    ["Rest Day OT", "payitem-id-10"],
    ["Retroactive Pay", "payitem-id-20"],
    ["Salary Loan Repayment", "payitem-id-51"],
    ["Special Holiday", "payitem-id-05"],
    ["Special Holiday ND", "payitem-id-05"],
    ["Special Holiday ND OT", "payitem-id-08"],
    ["Special Holiday OT", "payitem-id-08"],
    ["Special Holiday Premium Pay", "payitem-id-05"],
    ["Spot Bonus", "payitem-id-13"],
    ["SSS (ECC)", "payitem-id-40"],
    ["SSS (EE)", "payitem-id-37"],
    ["SSS (ER)", "payitem-id-39"],
    ["SSS Loan", "payitem-id-42"],
    ["SSS Provident Fund (EE)", "payitem-id-38"],
    ["SSS Provident Fund (ER)", "payitem-id-41"],
    ["SSS Regular EE", "payitem-id-37"],
    ["Tax Payable", "payitem-id-53"],
    ["Tax Refund", "payitem-id-23"],
    ["Tax Refund - Previous Year", "payitem-id-22"],
    ["Tax Refund 2024", "payitem-id-22"],
    ["Tax Withheld", "payitem-id-01"],
    ["Team Lead Allowance", "payitem-id-27"],
    ["Transportation Allowance", "payitem-id-28"],
    ["Tuition Fee Grant", "payitem-id-31"],
    ["Undertime/Tardiness", "payitem-id-36"]
]);

export const oldPayitemsNameToPayitemIDMap = (payitem) => {
    return payitemsMap.get(payitem);
};